## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

format="""
$username$directory$git_branch$cmd_duration
$character
"""

add_newline = true 

[username]
format = " [$user]($style)@"
style_user = "bold #adadad"
style_root = "bold red"
show_always = true


[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[ 󰊠](#63c0ee bold)"
error_symbol = "[ 󰊠](#f38ba8)"
vicmd_symbol = "[](#f9e2af)"

#[directory]
#format = "[]($style)[  ](fg:#81A1C1)[$path]($style)"
#style = "bg:none fg:#b3b3b3"
#truncation_length = 3
#truncate_to_repo=false

[git_branch]
format = "[]($style)[[  ](fg:#A2DD9D bold)$branch](fg:#86AAEC)[ ]($style)"
style = "bg:none fg:#161821"


[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[]( fg:#b3b3b3 bold)$duration](fg:#BBC3DF)[ ]($style)"
disabled = false
style = "bg:none fg:#161821"


# 
